namespace towerRedo.Services
{
  public class TicketsService
  {

    // TODO GET TICKET BY TICKET ID
    // TODO GET TICKET BY EVENT ID
    // TODO GET TICKETS BY ACCOUNT ID
    // TODO CREATE TICKET -- MAKE SURE TO DECREASE EVENT CAPACITY ON CREATE
    // TODO DELETE TICKET -- MAKE SURE TO INCREASE EVENT CAPACITY ON DELETE

  }
}